name: Post-Deployment Tasks
on: deployment_status
jobs:
  post-deploy:
    if: ${{ github.event.deployment.environment == 'Production' && github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
